# Generated by Django 2.1.3 on 2018-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.ImageField(blank=True, upload_to='products/small/%Y/%m/%d'),
        ),
    ]
