# Generated by Django 2.1.3 on 2018-12-08 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Новая почта', 'Новая почта'), ('Деливери', 'Деливери'), ('Укрпочта', 'Укрпочта'), ('Интайм', 'Интайм'), ('Самовывоз', 'Самовывоз'), ('', 'Не указано')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0991234567', max_length=15, validators=[django.core.validators.RegexValidator(message="Введите украинский телефонный номер в формате код оператора + номер телефона: '0671234567'. От 10 до 15 цифр.", regex='^\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправленно'),
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительная информция'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Почтовый индекс'),
        ),
    ]
